---
title: "Testing_song_ETA_Kevin"
author: "Kevin"
date: "2024-02-10"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(plotly)
library(tidyverse)
library(gtools)
```

```{r}
Spotify_song_attributes <- read.csv("Spotify_audio_features.csv")
colnames(Spotify_song_attributes)
#can join on uri
```

```{r}
Spotify_data <- read.csv("New_Spspotify_chart_song_ranks.csv")
Spotify_charts = Spotify_data %>% 
  mutate(artist_names = str_trim(artist_names), WeekDate = as.Date(WeekDate)) 
```

```{r}
colnames(Spotify_charts)
```
```{r}
number_of_weeks_total_of_all_songs_charts = Spotify_charts %>% 
  group_by(artist_names) %>% 
  summarize(total = n())  
hist(x =number_of_weeks_total_of_all_songs_charts$total, main = "Number of weeks totla of all songs combined artsit has been on the charts")

number_of_weeks_total = Spotify_charts %>% 
  group_by(artist_names) %>% 
  summarize(total = n()) %>% 
  filter(total >300)


hist(x =number_of_weeks_total$total, main = "Number of weeks totla of all songs combined artsit has been on the charts,slightly cut down to see rest of rankings")
```

```{r}
total_streams = Spotify_charts %>%
  group_by(artist_names) %>%
  mutate(total_streams = sum(streams),total_weeks = n()) %>%
  select(artist_names, total_streams,total_weeks) %>% 
  distinct() %>% 
  arrange(desc(total_streams))
total_streams 
```




## Looking at indivisual artist 
```{r}
artist_trim_data = Spotify_charts %>%
  filter(artist_names == "Taylor Swift")
```

```{r}
aa <- ggplot(data = artist_trim_data,aes(x= WeekDate ,y =streams,color = track_name)) + geom_line() +theme(legend.position = "none")
ggplotly(aa)
```
```{r}
total_streams = artist_trim_data %>%
  group_by(track_name) %>%
  mutate(total_streams = sum(streams),total_weeks = n()) %>%
  select(track_name, total_streams,total_weeks) %>% 
  distinct() %>%
  arrange(track_name)
```


```{r}
combined_df = merge(x= artist_trim_data ,y = Spotify_song_attributes,by.x = "uri",by.y = "uri")

duplicate_rows <- duplicated(combined_df$track_name)

unique_combined_df <- combined_df[!duplicate_rows, ]
unique_combined_df <- merge(x= unique_combined_df,y =total_streams, by.x = "track_name",by.y ="track_name" )
head(unique_combined_df )
```


```{r}
y_input = "speechiness"
x_input = "track_name"
size_input_1 = "total_streams"



ggplot(data = unique_combined_df, aes_string(y = y_input, x = x_input, size = size_input_1, color = size_input)) +
  geom_point(alpha = 0.7) +
  scale_size_continuous(range = c(3, 10)) +  # Adjust size range
  scale_color_viridis_c() +  # Add color scale
  labs(y = y_input, x = x_input, size = size_input_1, color = size_input_1) +
  theme_minimal()

```

```{r}
smaller_data = unique_combined_df %>% 
  select(tempo,valence,liveness,instrumentalness,acousticness,speechiness,loudness,energy,danceability,total_weeks)
smaller_data 
```

```{r}

ft_sets <- function(data, yName, maxFeatureSetSize) {
  row_data_combo <- list() # we should probaly delete this before turning in 
  col_names <- colnames(data)# get all the colum names 
  x_variables <- col_names[col_names != yName]# we are left with all the names not including sname of yname 
  
  for (i in 1:maxFeatureSetSize) {
    bb <- combinations(n = length(x_variables), r = i, v = x_variables)# this give us all the combonation of of size i for the columanes, but its in a matrix data 
    
    for (j in 1:nrow(bb)) {
      row_data_combo <- append(row_data_combo, list(bb[j, ]))# this take the matrix form and basicly takes each row of that matrix and adds to list row_data_combo
    }
  }
  
  return(row_data_combo)
}

```


```{r}
takeALookAround <- function(data, yName, maxFeatureSetSize) {
  row_combos <- ft_sets(data, yName, maxFeatureSetSize)
  output_data_frame <- data.frame(name = character(),
                                  Y_accuracy = numeric(),
                                  Y_S_accuracy = numeric(),
                                  S_accuracy = numeric(),
                                  stringsAsFactors = FALSE)
  
  for (column_indices in row_combos) {
    temp <- data[, c(column_indices, yName)]  # Include only selected columns and the yName
    
    if (is.numeric(data[, yName])) {
      model <- lm(paste(yName, "~ ."), data = temp)  # Linear regression model
      
      Y_accuracy <- summary(model)$adj.r.squared
    } else {
      model <- glm(paste(yName, "~ ."), data = temp, family = binomial)  # Logistic regression model
      
      Y_accuracy <- summary(model)$null.deviance
    }
    
    name <- paste(colnames(temp)[-which(colnames(temp) == yName)], collapse = "+")
    output_data_frame <- rbind(output_data_frame, 
                               data.frame(name = name,
                                          Y_accuracy = Y_accuracy,
                                          stringsAsFactors = FALSE))
  }
  
  return(output_data_frame)
}
```

```{r}
aaaa <- takeALookAround(smaller_data,"total_weeks",length(colnames(smaller_data))-1)
```

```{r}
aaaa %>% 
  arrange(desc(Y_accuracy))
```

